sudo: false
language: cpp
cache: apt

git:
  depth: 1

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - kalakris-cmake
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - libtool
    - gcc-4.8
    - g++-4.8
    - clang-3.4
    - make
    - cmake
    - libboost1.55-dev

install:
  # gcc 4.8
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  # - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

  - $CXX --version

  - mkdir bin
  - cd bin
  - cmake ../ -DCMAKE_BUILD_TYPE=Release

script:
  - make -j 4
  - ./ContinuableTests
